# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-13 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_item_unique_together'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to='list',
        ),
    ]
